### ISSUE TITLE
pkgin segfaults on upgrade

### ISSUE THREAD

**Issue by ghost** [NetBSDfr/pkgin#1]
I created a binary package using pkg_create and added to the repo.

pkg_info -X <package> >> pkg_summary was used to update the summary file.

pkgin install <packaage> was used to install the packge.

All worked fine.

pkgin upgrade caused a segfault:

[root@2f52fae8-983d-4425-a8bd-29f929cc995e /var/db/pkgin]# mdb /opt/local/bin/pkgin core
Loading modules: [ libumem.so.1 libc.so.1 ld.so.1 ]

> $C
> fffffd7fffdffa20 libc.so.1`strcmp+0x16()
> fffffd7fffdffa40 pkgin_upgrade+0x36()
> fffffd7fffdffb20 main+0x55f()
> fffffd7fffdffb30 _start+0x6c()

truss:

67017:  read(4, 0x006AE018, 1024)                       = 1024
67017:    \r\0\0\005\0 !\003 302 m01B0\0DA\0 !\0\0\0\0\0\0\0\0\0\0\0\0\0\0
67017:    \081 61E12\0 7 '1B E1D1D [15\0 /\01F17\017\0 p 5 - N e t - L i b
67017:     I D N - 0 . 1 2 n b 4 p 5 - N e t - L i b I D N 0 . 1 2 n b 4 P
67017:     e r l   b i n d i n g s   f o r   G N U   L i b i d n a r t i s
67017:     t i c 2 0 0 9 1 1 1 5 h t t p : / / s e a r c h . c p a n . o r
67017:     g / d i s t / N e t - L i b I D N / 5 . 1 1 n e t / p 5 - N e t
67017:     - L i b I D N n e t   p e r l 5 5 4 5 5 4 S u n O S81 S1D12\0 ;
67017:     -19 g\01D m15\0 ?\01D17\017\0 p k g _ i n s t a l l - i n f o -
67017:     4 . 5 n b 3 p k g _ i n s t a l l - i n f o 4 . 5 n b 3 S t a n
67017:     d a l o n e   G N U   i n f o   f i l e   i n s t a l l a t i o
67017:     n   u t i l i t y 2 0 0 9 1 1 1 5 h t t p : / / w w w . g n u .
67017:     o r g / s o f t w a r e / t e x i n f o / t e x i n f o . h t m
67017:     l 5 . 1 1 p k g t o o l s / p k g _ i n s t a l l - i n f o p k
67017:     g t o o l s 3 2 4 4 8 S u n O S81 :1C12\0 9 # ! e !1D 315\0 /\0
67017:    1F1F\017\0 s c m g i t - b a s e - 1 . 8 . 0 . 1 n b 1 s c m g i
67017:     t - b a s e 1 . 8 . 0 . 1 n b 1 G I T   T r e e   H i s t o r y
67017:       S t o r a g e   T o o l   ( b a s e   p a c k a g e ) g n u -
67017:     g p l - v 2 2 0 0 9 1 1 1 5 h t t p : / / g i t - s c m . c o m
67017:     / 5 . 1 1 d e v e l / s c m g i t - b a s e d e v e l   s c m 2
67017:     0 7 2 7 8 0 3 8 S u n O S81 C1B12\0 )151F ] 91D 515\0 ! / -1D\0
67017:    17\0 p e r l - 5 . 1 6 . 2 n b 2 p e r l 5 . 1 6 . 2 n b 2 P r a
67017:     c t i c a l   E x t r a c t i o n   a n d   R e p o r t   L a n
67017:     g u a g e g n u - g p l - v 2   O R   a r t i s t i c 2 0 0 9 1
67017:     1 1 5 h t t p : / / w w w . p e r l . o r g / 5 . 1 1 l a n g /
67017:     p e r l 5 6 4 b i t a u t o   t h r e a d s l a n g   d e v e l
67017:       p e r l 5 6 1 5 8 3 5 3 5 S u n O S81 J1A12\0 5 #1D y %1D 915
67017:    \0 5171D1B\017\t p k g _ i n s t a l l - 2 0 1 2 0 2 2 1 p k g _
67017:     i n s t a l l 2 0 1 2 0 2 2 1 P a c k a g e   m a n a g e m e n
67017:     t   a n d   a d m i n i s t r a t i o n   t o o l s   f o r   p
67017:     k g s r c m o d i f i e d - b s d 2 0 0 9 1 1 1 5 h t t p : / /
67017:     w w w . p k g s r c . o r g / 5 . 1 1 p k g t o o l s / p k g _
67017:     i n s t a l l i n e t 6 p k g t o o l s 2 2 5 7 5 1 2 S u n O S
67017:  brk(0x006C8000)                                 = 0
67017:      Incurred fault #6, FLTBOUNDS  %pc = 0xFFFFFD7FFF1782D6
67017:        siginfo: SIGSEGV SEGV_MAPERR addr=0x00000000
67017:      Received signal #11, SIGSEGV [default]
67017:        siginfo: SIGSEGV SEGV_MAPERR addr=0x00000000

FIX:

pkgin unkeep <package.

pkgin upgrade

--> works?!?!

**Comment by Licenser** [comment]
@iMilnb you should claim https://www.bountysource.com/issues/914106-pkgin-segfaults-on-upgrade ;)
