### ISSUE TITLE
Incorrect version comparison logic

### ISSUE THREAD

**Issue by suominen** [NetBSDfr/pkgin#108]
I installed a local package ([`gw-base`](https://github.com/suominen/pkgsrc-gw/tree/main/gw-base)), which depends on `jq`, which in turn depends on `oniguruma`. The repository had the following versions of `oniguruma` available:

- `oniguruma-6.9.6.tgz`
- `oniguruma-6.9.6rc4.tgz`

The version that `pkgin in gw-base` picked was `oniguruma-6.9.6rc4` while the correct version would have been `oniguruma-6.9.6`.

Running `pkg_add gw-base` against the same repository correctly results in `oniguruma-6.9.6` having been installed.

**Comment by jperkin** [comment]
This should be fixed in https://github.com/NetBSDfr/pkgin/commit/4653f3cb484cc8f36d5b02fd4a459d54a4cd511a, are you able to build a local pkgin with that patch to verify?

**Comment by jperkin** [comment]
Hmm no, there's still an issue.  It's now fine when it's a top-level package, but dependencies are still being calculated incorrectly.

```
$ sudo ./pkgin -n install nodejs

1 package to install:
nodejs-14.15.3
```

```
$ sudo ./pkgin -n install npm

2 packages to install:
npm-6.14.9
nodejs-8.17.0nb4
```
