### ISSUE TITLE
pkgin fails to recognise the correct arch

### ISSUE THREAD

**Issue by pettai** [NetBSDfr/pkgin#13]
See pkg/46071
http://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=46071

**Comment by Saulius-Krasuckas** [comment]
The report ends with:

> State-Changed-From-To: open->closed
> State-Changed-By: jperkin@NetBSD.org
> State-Changed-When: Mon, 20 Apr 2020 10:36:58 +0000
> State-Changed-Why:
> Closing this one out, it's likely things have changed since this was
> originally reported, certainly now pkgin is consistent in how it handles
> MACHINE_ARCH and if there is a mismatch reported then there is a genuine
> mismatch that needs to be investigated.

@pettai, is this still the case?

**Comment by pettai** [comment]
No, I don't think so (and I don't think the host that had this issue is alive), this was a long time ago...
