### ISSUE TITLE
pkgin documentation needs improvements

### ISSUE THREAD

**Issue by 0-wiz-0** [NetBSDfr/pkgin#16]
Some topics that should be covered:
Where is pkgin's database?
What are the files in /var/db/pkgin/ for?
What happens when you give an argument to pkgin fug or pkgin ug?
Can the cache directory be changed (/var might not be big enough) or cleaned?
Is 'keepable' the same as 'automatic=YES'?
Why does pkgin keep its own database?
Why is there even an upgrade command? (Doesn't everyone use fug?)
Perhaps document that 'pkgin -n ar' can be used to show packages that are possibly not necessary.

**Comment by iMilnb** [comment]
Thanks for all those inputs, I've added them to the last commit.
