### ISSUE TITLE
make pkgin standalone

### ISSUE THREAD

**Issue by 0-wiz-0** [NetBSDfr/pkgin#18]
Currently, pkgin is basically a frontend for pkg_add and pkg_delete, calling the executables when needed.
It would be good if it was standalone instead.

The pkg_install tools already provide much functionality in a library, but the main add/delete functionality is in add/perform.c and delete/pkg_delete.c respectively. Perhaps a first step would be to refactor them into the library. (This part is not directly pkgin relevant, but the end goal is.)

**Comment by gdt** [comment]
I'm not sure this is a good idea.   Right now the tools are used, and thus are responsible for database invariants.   But I guess in 9 years it hasn't happened, so the risk feels low :-)

**Comment by jperkin** [comment]
Yeh this basically isn't going to happen, and while I'd like to do something like this, it would be a from-scratch implementation that shares no code with pkgin and would likely be written in rust with a completely rewritten pkgdb.

**Comment by gdt** [comment]
rust isn't going to work on most of the platforms that pkgsrc supports.    So   I guess you should just close this as WONTFIX, because at this point the cognitive load of it being open while scanning tickets seems to be higher than the use of knowing it could happen.

**Comment by 0-wiz-0** [comment]
I take it it's not going to happen - I can live with that :)

**Comment by sskras** [comment]
@jperkin commented [yesterday](https://github.com/NetBSDfr/pkgin/issues/18#issuecomment-1684059689):

> it would be a from-scratch implementation that shares no code with pkgin and would likely be written in rust with a completely rewritten pkgdb.

Something like https://github.com/jperkin/pm ?

**Comment by jperkin** [comment]
> @jperkin commented [yesterday](https://github.com/NetBSDfr/pkgin/issues/18#issuecomment-1684059689):
> 
> > it would be a from-scratch implementation that shares no code with pkgin and would likely be written in rust with a completely rewritten pkgdb.
> 
> Something like https://github.com/jperkin/pm ?

Yeh, along those lines. That is a start at reimplementing the existing packaging tools and pkgdb in rust, but if I had time I'd also explore a proper transactional pkgdb.
