### ISSUE TITLE
smarter library handling

### ISSUE THREAD

**Issue by 0-wiz-0** [NetBSDfr/pkgin#19]
When running "pkgin fug", the user can end up with unusable programs if a shlib was bumped and the necessary PKGREVISION bumps were forgotten in pkgsrc.
However, pkgin does have enough information to avoid this or fix it, so it would be good if it did.

More details:
Let's assume libfoo was bumped from 2.0 to 2.1, and nobody expected the shlib major to change, but it did.
libbar depends on it but it's PKGREVISION wasn't bumped.

On the local system, libfoo and libbar are installed. Currently, if one runs "pkgin fug", libfoo is updated and libbar is broken, since the old libfoo library is missing.
The easiest solution would be to check the PLISTs before upgrading and verify that the REQUIRES lines of all dependencies are still fulfilled (from /var/db/pkg/*/+BUILD_INFO), and stop/skip the package upgrade if not.

Usually, a bulk build machine will rebuild libbar, so there might be a newer binary package for libbar available, with the same PKGREVISION, but depending on the newer libfoo, so alternatively, libbar could be reinstalled from the newer binary package instead.

**Comment by jperkin** [comment]
This type of bug was resolved with the introduction of refresh support in 0.10.0.  Sorry it took so long to close out the issue!
