### ISSUE TITLE
pkgin don't work "out-of-the-box"

### ISSUE THREAD

**Issue by olear** [NetBSDfr/pkgin#23]
pkgin don't work "out-of-the-box" like it should.

Example:

[root@localhost ~]# rm -rf /usr/pkg\* /var/db/pkg*
[root@localhost ~]# echo http://bob.dracolinux.org/pkgsrc/packages/stable/All > /etc/pkgin/repositories.conf

[root@localhost ~]# pkgin install perl
Database needs to be updated.
proceed ? [Y/n] y
empty available packages list
nothing to do.

This should not happen, but when I do:

[root@localhost ~]# mkdir /var/db/pkg

and then run install again:

[root@localhost ~]# pkgin install perl
Database needs to be updated.
proceed ? [Y/n] y
pkg_summary.bz2                                                                                       100% 5565     5.4KB/s   5.4KB/s   00:00  
processing remote summary (http://bob.dracolinux.org/pkgsrc/packages/stable/All)...
updating database: 100%
calculating dependencies... done.
nothing to do.

The database was updated, but no packages was installed. This should not happen. If I manually install a package (any package):

[root@localhost ~]# pkg_add http://bob.dracolinux.org/pkgsrc/packages/stable/All/digest-20121220.tgz

And run install again:

[root@localhost ~]# pkgin install perl
reading local summary...
processing local summary...
updating database: 100%
calculating dependencies... done.

nothing to upgrade.
1 packages to be installed: perl-5.18.2nb1 (16M to download, 60M to install)

proceed ? [Y/n] 

Now I can install a package. I should be able to use pkgin on a "clean install".

**Comment by jperkin** [comment]
This was fixed a while back.
