### ISSUE TITLE
confusing error message stops pkgin in its tracks

### ISSUE THREAD

**Issue by 0-wiz-0** [NetBSDfr/pkgin#24]
After finishing a bulk build, I wanted to upgrade the installed packages, but couldn't:

```
# pkgin up
pkg_summary.bz2                      100%  295KB 295.0KB/s 295.0KB/s   00:00
processing remote summary (file:///archive/packages/current/All)...
updating database: 100%
# pkgin fug
calculating dependencies... done.
pkgin: vlc-2.1.4nb1 has no associated repository
```

I hadn't seen this message before, even if vlc has been there for some time, and whatever the error means, I don't think it should stop the upgrade -- just skip vlc.

**Comment by jperkin** [comment]
I think this was resolved a few years ago, but certainly 23.8.0 should avoid this, unless there are new corner cases I'm not aware of. Will close for now and if it happens again we can get a proper test case for it.
