### ISSUE TITLE
pkgin does not update database when repository removed from repositories.conf

### ISSUE THREAD

**Issue by jlmuir** [NetBSDfr/pkgin#33]
I have the following in repositories.conf:

```
file:///usr/pkgsrc/packages/All
http://ftp.NetBSD.org/pub/pkgsrc/packages/NetBSD/amd64/6.1.4/All
```

I do an update:

```
$ pkgin update -f           
pkg_summary.bz2                     100% 5371     5.3KB/s   5.3KB/s   00:00    
processing remote summary (file:///usr/pkgsrc/packages/All)...
updating database: 100%
pkg_summary.bz2                     100% 2176KB 725.5KB/s 514.4KB/s   00:03    
processing remote summary (http://ftp.NetBSD.org/pub/pkgsrc/packages/NetBSD/amd64/6.1.4/All)...
updating database: 100%
```

I check the list of available packages:

```
$ pkgin avail | less
```

Looks good.

Now I remove the NetBSD.org repo from repositories.conf, leaving just the local repo:

```
file:///usr/pkgsrc/packages/All
```

I do an update:

```
$ pkgin update -f
database for file:///usr/pkgsrc/packages/All is up-to-date
```

Hmm, nothing about the fact that I removed the remote repo.  Let's check the list of available packages:

```
$ pkgin avail | less
```

Wrong.  I removed the remote repo from repositories.conf, yet it still lists all the packages from that repo.

A workaround is to touch the pkg_summary.bz2 file of the local repo:

```
$ touch /usr/pkgsrc/packages/All/pkg_summary.bz2
```

I do an update, and now it realizes that the remote repo has been removed:

```
$ pkgin update -f           
pkg_summary.bz2                     100% 5371     5.3KB/s   5.3KB/s   00:00    
cleaning database from http://ftp.NetBSD.org/pub/pkgsrc/packages/NetBSD/amd64/6.1.4/All entries...
processing remote summary (file:///usr/pkgsrc/packages/All)...
updating database: 100%
```

I used the latest version of pkgin from GitHub (cloned on August 25, 2014; latest commit:  413f8a89dd09018464e01f7be3f77ff1b76a1545) on NetBSD 6.1.4 (GENERIC) amd64.

This issue may be related to issue #3.

**Comment by iMilnb** [comment]
This issue should be fixed by latest commit, could you give it a try?

**Comment by iMilnb** [comment]
Fix working, confirmed from many sources.
