### ISSUE TITLE
pkgin uses "pkg_add -f"

### ISSUE THREAD

**Issue by gdt** [NetBSDfr/pkgin#40]
I had xentools41 installed, and did "pkgin in xentools24".   This should have failed, because xentools42 conflicts with xentools41 because PLISTs overlap.  pkg_add rejects this addition.  As a result, I had a mix of the packages, and when I removed xentools42 the xentools41 package was broken.   It seems this happens because -f is pased to pkg_add.

This is a critical integrity failure;  it should not be possible to reach unsafe states with pkgin.  pkgin should never use -f with pkg_add.   I really do mean never; if some specific check needs overriding for a good reason, there should be a flag to just skip that.  (Arguably, pkg_add/etc. should have a coherent scheme of named checks with a flexible override mechanism.)

**Comment by iMilnb** [comment]
pkgin has been modified in order to use `pkg_add -D` instead, could you try it and tell us if it behaves as expected?
