### ISSUE TITLE
"pkgin ar" output is hard to read

### ISSUE THREAD

**Issue by gdt** [NetBSDfr/pkgin#41]
When running "pkgin ar", the list is unreadable because the package names are space-separated on one long line.   While I know how to use tr, the default should be one package per line.  With "pkgin -n ar", it should just output the list to be removed, with nothing else, similar to "pkgin sk" (except without any superfluous text).

**Comment by iMilnb** [comment]
I really like the idea of showing one package per line when `-n` is provided, will definitely add that one, thanks.

**Comment by iMilnb** [comment]
Feature available on latest commit.
