### ISSUE TITLE
pkgin should ask about upgrading pkg_install before removing other packages

### ISSUE THREAD

**Issue by jeffrizzo** [NetBSDfr/pkgin#57]
I recently did a 'pkgin full-upgrade' over ssh, which of course can take a long time.  The problem I ran into was this prompt:

about to upgrade pkg_install, proceed ? [Y/n]

I didn't realize it was coming, and it only happened after downloading all the packages, and ACTUALLY REMOVING the packages it was upgrading.

I got distracted, and then a network problem closed my ssh connection - which meant nearly all my packages were deleted and there was no easy way to recover.

When working interactively, pkgin should get answers to all questions BEFORE removing anything to avoid this sort of issue.

**Comment by jperkin** [comment]
pkgin no longer does this, sorry it took so long to close the issue.
