### ISSUE TITLE
pkgin installation requires pkgsrc

### ISSUE THREAD

**Issue by eliteraspberries** [NetBSDfr/pkgin#65]
Hello. The install target is in the pkgsrc Makefile rather than the pkgin one. It would be nice to install pkgin independent of pkgsrc.

**Comment by tangledhelix** [comment]
+1

**Comment by jperkin** [comment]
This will have been fixed in a0c974c2ee40c8f996938a368b8c3c9922ffb91b and subsequent releases. Apologies for not seeing this sooner!
