### ISSUE TITLE
corrupted database when CTRL-C'ing a pkgin process

### ISSUE THREAD

**Issue by Licenser** [NetBSDfr/pkgin#66]
When running a pkgin command and aborting it with ctrl-C there is a high chance that it results in a corrupted database rendering pgkin un-usable.

**Comment by jperkin** [comment]
Which version?  Since 0.9.x last year it should be more resilient to updates.  I cannot produce a corrupt db by CTRL-C'ing during a `pkgin up`.

**Comment by Licenser** [comment]
The problem here is that it is timing related, I've never been able to reliably reproduce it, there seems to be some moment when installing packages in which it is 'vulnerable'. I tried a dozen times today and didn't see it, but it might just be hitting the CTRL-C in the wrong moment.

**Comment by jperkin** [comment]
But have you seen it happen since running 0.9.x?

**Comment by jperkin** [comment]
Any leftover corner cases should have been resolved in efc39b787f6db4ebb97ae8a2340338c5ac7d92f9 and version 22.9.0.
