### ISSUE TITLE
OS version change does not make package appear to need upgrades

### ISSUE THREAD

**Issue by gdt** [NetBSDfr/pkgin#76]
On a machine running netbsd-6/i386, I upgraded to netbsd-7.  I changed my pkgin config file and did "pkgin up".  In my view, packages built on netbsd-6 are out of date because they are possibly linked with old libraries.  As long as one uses only those packages, it will work because of binary compatibility, but updating to mixed versions will be trouble.  Therefore, I think packages should be viewed as needing upgrades if the build OS version is different, or there should be some flag to ug/fug to enable this.

**Comment by jperkin** [comment]
This will have been resolved as part of the refresh work in 0.10.0 and newer. Sorry it took so long to close out the issue.
