### ISSUE TITLE
Provide useful progress during upgrade

### ISSUE THREAD

**Issue by 0-wiz-0** [NetBSDfr/pkgin#95]
When running pkgin to upgrade 250 packages (which can easily happen when switch from one branch to the next), you see a lot of lines like
````
upgrading foo...
installing bar...
````
but there is no way to guess how far along in the upgrade one is.
One idea would be to add "[x/y]" before the `upgrading` or `installing` part (package number `x` from a total of `y` packages that are modified by `pkgin` in this process).

**Comment by jperkin** [comment]
Fixed in 23.8.0, all installs and downloads now have counters.

**Comment by 0-wiz-0** [comment]
Works well, thank you!
