### ISSUE TITLE
pkgin export puts stderr-like text to stdout

### ISSUE THREAD

**Issue by gdt** [NetBSDfr/pkgin#97]
pkgin export outputs to stdout sometimes:

processing local summary...
reading local summary...

The output is not wrong, as I had done manual pkg_add, but it belongs on stderr.

**Comment by jperkin** [comment]
I don't want to move it to `stderr` as it legitimately belongs on `stdout` for most operations, but at least now it won't affect operations such as `pkgin export`.

I've added a test for this in the test suite, and will close the issue out once a new release has been cut.

**Comment by sskras** [comment]
Thanks for the update.

> I've added a test for this in the test suite, 

Is it an external thing or something in the tree that I fail to find? :)

**Comment by jperkin** [comment]
> Is it an external thing or something in the tree that I fail to find? :)

https://github.com/TritonDataCenter/pkgin-test-suite/commit/dbd2607695dc6a5915c1d637a66827c5e061e575

**Comment by jperkin** [comment]
Fixed in 23.8.0.
