### ISSUE TITLE
pkgin loses info about packages removed due to failures

### ISSUE THREAD

**Issue by gdt** [NetBSDfr/pkgin#98]
I tried to upgrade a package foo, and the install of the replacement failed (for various reasons that were correct about dependencies of foo, due to a repo that was not quite right).  pkgin no longer knew that foo should be installed, so pkgin ar would remove foo's dependencies, and pkgin fug would not put foo back even after I fixed the repo.

A suggested fix is to have a list of packages that should be installed but aren't (keepable only probably) in the db, and to have pkgin fug try to install them, or some other command.

**Comment by jperkin** [comment]
This should be fixed in 23.8.0, as packages are now correctly registered in pkgdb as they are installed (by using the `-A` flag to `pkg_add`).
